import { Product, ProductsData } from '@/types';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'hp-elitebook-840-g8',
    name: 'HP EliteBook 840 G8',
    brand: 'HP',
    category: 'Ordinateurs portables',
    condition: 'Occasion A+',
    price: 225000,
    originalPrice: 280000,
    images: [
      { url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=90', alt: 'HP EliteBook 840 G8' },
      { url: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=90', alt: 'HP EliteBook 840 G8 clavier' },
    ],
    specs: {
      processor: 'Intel Core i5-1135G7 (11ème génération)',
      ram: '16 Go DDR4 3200 MHz',
      storage: '512 Go SSD NVMe',
      display: '14" Full HD IPS Anti-reflet (1920×1080)',
      graphics: 'Intel Iris Xe Graphics',
      battery: 'Jusqu\'à 12h d\'autonomie',
      os: 'Windows 11 Pro',
      connectivity: 'Wi-Fi 6, Bluetooth 5.0, USB-C Thunderbolt 4',
    },
    included: ['Chargeur d\'origine HP', 'Sacoche de transport offerte', 'Souris sans fil offerte'],
    warranty: '6 mois pièces et main-d\'œuvre',
    stockStatus: 'En stock',
    description: 'Un ultrabook professionnel haut de gamme, idéal pour les cadres et entrepreneurs. Châssis aluminium, écran anti-reflet et sécurité renforcée (lecteur d\'empreintes, TPM 2.0).',
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dell-latitude-5520',
    name: 'Dell Latitude 5520',
    brand: 'Dell',
    category: 'Ordinateurs portables',
    condition: 'Occasion A+',
    price: 195000,
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=90', alt: 'Dell Latitude 5520' },
    ],
    specs: {
      processor: 'Intel Core i7-1165G7 (11ème génération)',
      ram: '16 Go DDR4',
      storage: '256 Go SSD',
      display: '15.6" Full HD (1920×1080)',
      graphics: 'Intel Iris Xe',
      battery: 'Jusqu\'à 10h',
      os: 'Windows 11 Pro',
      connectivity: 'Wi-Fi 6, Bluetooth 5.1, USB-C',
    },
    included: ['Chargeur Dell d\'origine'],
    warranty: '6 mois',
    stockStatus: 'En stock',
    description: 'Le Latitude 5520 est la référence professionnelle de Dell. Robuste, léger et puissant pour une productivité maximale.',
    featured: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'lenovo-thinkpad-t14-gen2',
    name: 'Lenovo ThinkPad T14 Gen 2',
    brand: 'Lenovo',
    category: 'Ordinateurs portables',
    condition: 'Occasion A+',
    price: 210000,
    images: [
      { url: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=90', alt: 'Lenovo ThinkPad T14' },
    ],
    specs: {
      processor: 'AMD Ryzen 7 Pro 5850U',
      ram: '16 Go DDR4',
      storage: '512 Go SSD NVMe',
      display: '14" Full HD IPS',
      graphics: 'AMD Radeon RX Vega 8',
      battery: 'Jusqu\'à 14h',
      os: 'Windows 11 Pro',
      connectivity: 'Wi-Fi 6, Bluetooth 5.0, USB-C',
    },
    included: ['Chargeur Lenovo', 'Sacoche offerte'],
    warranty: '6 mois',
    stockStatus: 'Stock limité',
    description: 'Le ThinkPad légendaire. Fiabilité militaire, clavier exceptionnel, autonomie record. Le choix des professionnels exigeants.',
    featured: true,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
  {
    id: 'hp-prodesk-600-g5',
    name: 'HP ProDesk 600 G5 SFF',
    brand: 'HP',
    category: 'Ordinateurs de bureau',
    condition: 'Occasion A+',
    price: 145000,
    images: [
      { url: 'https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&q=90', alt: 'HP ProDesk bureau' },
    ],
    specs: {
      processor: 'Intel Core i5-9500',
      ram: '8 Go DDR4',
      storage: '256 Go SSD',
      graphics: 'Intel UHD Graphics 630',
      os: 'Windows 11 Pro',
      connectivity: 'USB 3.1, DisplayPort, VGA',
    },
    included: ['Clavier HP', 'Souris HP'],
    warranty: '3 mois',
    stockStatus: 'En stock',
    description: 'PC de bureau compact haute performance pour le bureau. Idéal pour les équipes comptables, administratives et PME.',
    featured: false,
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-04T00:00:00Z',
  },
  {
    id: 'dell-optiplex-7080',
    name: 'Dell OptiPlex 7080 Mini Tower',
    brand: 'Dell',
    category: 'Ordinateurs de bureau',
    condition: 'Occasion A+',
    price: 175000,
    images: [
      { url: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=800&q=90', alt: 'Dell OptiPlex 7080' },
    ],
    specs: {
      processor: 'Intel Core i7-10700',
      ram: '16 Go DDR4',
      storage: '512 Go SSD + 1 To HDD',
      graphics: 'AMD Radeon RX 640 4Go',
      os: 'Windows 11 Pro',
      connectivity: 'USB 3.2, DisplayPort, HDMI, Wi-Fi',
    },
    included: ['Clavier Dell', 'Souris Dell', 'Câble d\'alimentation'],
    warranty: '6 mois',
    stockStatus: 'En stock',
    description: 'PC de bureau professionnel polyvalent. Idéal pour les créatifs, les développeurs et les stations de travail intensives.',
    featured: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'hp-mf-neverstop-laser',
    name: 'HP Neverstop Laser MFP 1200w',
    brand: 'HP',
    category: 'Matériel bureautique',
    condition: 'Neuf',
    price: 185000,
    images: [
      { url: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&q=90', alt: 'Imprimante HP Neverstop' },
    ],
    specs: {
      processor: 'Impression: 20 ppm',
      ram: 'Résolution: 600×600 dpi',
      storage: 'Capacité: 2000 pages/toner',
      connectivity: 'Wi-Fi, USB, Application HP',
    },
    included: ['Cartouche laser incluse', 'Câble USB', 'Guide d\'installation'],
    warranty: '1 an constructeur',
    stockStatus: 'En stock',
    description: 'L\'imprimante laser multifonction révolutionnaire avec réservoir rechargeable. Économies garanties sur le long terme pour les entreprises.',
    featured: false,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
  },
  {
    id: 'logitech-mx-master-3',
    name: 'Logitech MX Master 3',
    brand: 'Logitech',
    category: 'Accessoires',
    condition: 'Neuf',
    price: 35000,
    images: [
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=90', alt: 'Souris Logitech MX Master 3' },
    ],
    specs: {
      connectivity: 'Bluetooth Low Energy, Nano récepteur USB Unifying',
      battery: 'Jusqu\'à 70 jours (recharge USB-C)',
    },
    included: ['Récepteur USB Unifying', 'Câble USB-C'],
    warranty: '2 ans Logitech',
    stockStatus: 'En stock',
    description: 'La souris ergonomique ultime pour les professionnels. Défilement électromagnétique MagSpeed, compatible multi-appareils.',
    featured: false,
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'onduleur-apc-650va',
    name: 'APC Back-UPS 650VA',
    brand: 'APC',
    category: 'Matériel bureautique',
    condition: 'Neuf',
    price: 55000,
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=90', alt: 'Onduleur APC 650VA' },
    ],
    specs: {
      processor: 'Puissance: 650 VA / 400W',
      ram: 'Autonomie: 5 à 10 minutes sous charge complète',
      connectivity: '8 prises de protection, USB',
    },
    included: ['Câble USB', 'Notice', 'Câble d\'alimentation'],
    warranty: '2 ans APC',
    stockStatus: 'Stock limité',
    description: 'Protection complète contre les coupures de courant et les surtensions. Indispensable pour tout équipement informatique professionnel en Afrique.',
    featured: false,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
];

export const DEFAULT_PRODUCTS_DATA: ProductsData = {
  products: SEED_PRODUCTS,
  updatedAt: new Date().toISOString(),
};
